In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mylinearregression import MyLinearRegression as MyLR
from utils import data_spliter, r2score_

In [2]:
df = pd.read_csv("../data/data.csv")
df

km  price
0   240000   3650
1   139800   3800
2   150500   4400
3   185530   4450
4   176000   5250
5   114800   5350
6   166800   5800
7    89000   5990
8   144500   5999
9    84000   6200
10   82029   6390
11   63060   6390
12   74000   6600
13   97500   6800
14   67000   6800
15   76025   6900
16   48235   6900
17   93000   6990
18   60949   7490
19   65674   7555
20   54000   7990
21   68500   7990
22   22899   7990
23   61789   8290

In [3]:
X = np.array(df['km']).reshape(-1,1)
Y = np.array(df['price']).reshape(-1,1)
X

array([[240000],
       [139800],
       [150500],
       [185530],
       [176000],
       [114800],
       [166800],
       [ 89000],
       [144500],
       [ 84000],
       [ 82029],
       [ 63060],
       [ 74000],
       [ 97500],
       [ 67000],
       [ 76025],
       [ 48235],
       [ 93000],
       [ 60949],
       [ 65674],
       [ 54000],
       [ 68500],
       [ 22899],
       [ 61789]])

In [4]:
X.shape

(24, 1)

In [5]:
x_train, x_test, y_train, y_test = data_spliter(X, Y, 0.8)

### LERNING  USE NORMALIZATION

In [8]:
MylR1 = MyLR(np.array([0,0]).reshape(-1, 1).astype('float64'), alpha=1e-3, max_iter=1000, normalize='y')

In [9]:
MylR1.fit_(x_train, y_train)




before denormalization [0.36213753 0.0350906 ]
after denormalization [5.33031814e+03 8.49062035e-04]


(array([[5.33031814e+03],
        [8.49062035e-04]]),
 array([[0.36213753],
        [0.0350906 ]]))

In [11]:
MylR1.fit_(X, Y)



before denormalization [ 2181.7289168  -1139.80855998]
after denormalization [ 1.01268722e+07 -2.43606051e+01]


(array([[ 1.01268722e+07],
        [-2.43606051e+01]]),
 array([[ 2181.7289168 ],
        [-1139.80855998]]))

In [13]:

model =MyLR(thetas=np.array([[0], [0]]).astype('float64'), alpha=1e-3, max_iter=10000)
for epoch in range(1):
    normalized, not_normalized = model.fit_(X, Y)
    Y_PRED = model.predict_(X)
    mse = model.mse_(Y, Y_PRED)
    r2 = r2score_(Y, Y_PRED)
    model.thetas = not_normalized
    middle_absolute = np.sqrt((model.cost_(X,Y)) / len(X))
    print("MSE:")
    print(model.cost_(X,Y) / len(X))
    print(f'MSE: {mse:.2f}, R2 Score: {r2:.2f}\n')
    print(f"middle_absolute: {middle_absolute}")
    model.thetas = not_normalized




before denormalization [ 0.66516359 -0.27995601]
after denormalization [ 6.73635906e+03 -5.98337127e-03]
MSE:
28688397.680143926
MSE: 1377043088.65, R2 Score: -824.11

middle_absolute: 5356.15512099341


In [24]:
MylR1 = MyLR(np.array([0,0]).reshape(-1, 1).astype('float64'), alpha=1e-3, max_iter=10000)
MylR1.fit_(x_train, y_train)

Y_PRED = MylR1.predict_(x_test)
#print(Y_PRED)
print("MSE:")
print(MylR1.cost_(x_test,y_test) / len(x_test))
print(f"Middle absolute: {np.sqrt((MylR1.cost_(x_test,y_test)) / len(x_test))}")
print(f"R2 score: {r2score_(y_test, Y_PRED)}")

ETA: 3.24s [100%] |████████████████████████████████████████| 9999/9999 | elapsed time 3.24ss

before denormalization [ 0.73485227 -0.2959486 ]
after denormalization [ 6.83925887e+03 -5.91621838e-03]
MSE:
218017.34230150335
Middle absolute: 466.9232723922672
R2 score: 0.17866173839555166
